### ISSUE TITLE
Non-blocking locks not restricting new locks being acquired

### ISSUE THREAD

**Issue by Nemi5150** [soulseekah/wp-lock#5] opened 2020-10-09 18:10 UTC
I need to use a non-blocking lock so that if the code does not get a new lock it just bails instead of waiting to run. I use it to keep multiple wp cron jobs from running at the same time. 

Here is the code I am using:
`   

    $processing_expired_auctions_lock = new WP_Lock( "_processing_expired_auctions" );
    $lock_aquired = $processing_expired_auctions_lock->acquire( WP_Lock::WRITE, false, 58 );
    error_log("Attempted to acquire lock");
    error_log(print_r($lock_aquired, true));

    if (!$lock_aquired) {
        error_log("lock failed");
        return;
    }
    error_log("lock succeeded");

    sleep(15);
    error_log("after sleep");

`

I sleep the thread to simulate a long running cron in my dev environment. The first time the lock is acquired. If I run the cron again before the 15 seconds is up, a lock is acquired again. The `$lock_acquired` variable is always 1;

**Comment by Nemi5150** [comment] 2020-10-09 18:59
More info, changing the lock type to , WP_Lock_Backend_wpdb works. I now get a "lock failed" in the logs

```
$processing_expired_auctions_lock = new WP_Lock( "_processing_expired_auctions", new WP_Lock_Backend_wpdb () );
$lock_acquired = $processing_expired_auctions_lock->acquire( WP_Lock::WRITE, false, 58 );
error_log("Attempted to acquire lock");
error_log(print_r($lock_acquired, true));

if (!$lock_acquired) {
    error_log("lock failed");
    return;
}
error_log("lock succeeded");

sleep(15);
error_log("after sleep");
```

**Comment by soulseekah** [comment] 2020-10-10 14:43
Hey! Thanks for the reports.

So the problem is only apparent with the `flock` backend?

**Comment by Nemi5150** [comment] 2020-10-10 15:34
Yes, the wpdb backend is working for me in testing. The flock backend is
exhibiting this problem.

**Comment by soulseekah** [comment] 2020-10-10 15:37
What platform are you on, PHP version, etc.?

**Comment by Nemi5150** [comment] 2020-10-10 15:53
Windows 10
Using DesktopServer version 3.9.4 https://serverpress.com/
php version 7.3.1
using latest wordpress

**Comment by soulseekah** [comment] 2020-10-10 17:35
Ah, that platform... yeh, I don't think it was supposed to work on Windows even.

https://www.php.net/manual/en/function.flock.php some people are reporting issues here...

If you try on a Linux machine it should work well, then we'll close it as a platform incompatibility.

Thanks.

**Comment by Nemi5150** [comment] 2020-10-10 18:11
I have no good way to test it on Linux and since the db backend is working
I will just use that. Thanks for getting back to me.

**Closed as completed** 2023-05-10 16:35 UTC
